version: '3.7'

services:
  db:
    image: postgres:13.0
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    stdin_open: true
    tty: true
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    links:
      - db
    restart: always

volumes:
  pg_data: