# Generated by Django 3.1.3 on 2020-11-16 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import images_app.images.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images_app.images.models.image_upload_to, validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])],
                                            verbose_name='Image')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
