# Generated by Django 3.1.3 on 2020-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('images', '0002_temporaryimagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_height', models.PositiveIntegerField(unique=True, verbose_name='Thumbnail height')),
                ('thumbnail_prefix',
                 models.CharField(help_text='Thumbnail file name will be start for this prefix', max_length=10,
                                  unique=True, verbose_name='Thumbnail prefix')),
                ('display_name', models.CharField(blank=True,
                                                  help_text='Value used as a key value in response in order to '
                                                            'recognize thumbnail',
                                                  max_length=20, verbose_name='Display name')),
            ],
        ),
    ]
